config/routes.rb
Supershoes::Application.routes.draw do
  get "static_pages/home"
  get "static_pages/help"
  get 'help'                            => 'static_pages#help',   :as => :help
  resources :articles
  resources :stores
  get 'services'                        => 'services#index',      :as => :services
  get 'services/stores'
  get 'services/articles'
  get 'services/articles/stores/:st_id' => 'services#stores',     :as => :services_articles_by_store
  root 'static_pages#home',                                       :as => :home
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :store
	validates_presence_of :name
	validates_length_of :name, :maximum => 30
	validates_presence_of :description
	validates_presence_of :price
	validates_numericality_of :price
	validates_numericality_of :total_in_shelf
	validates_numericality_of :total_in_vault
	validates_presence_of :store_id
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :articles
	validates_presence_of :name
	validates_length_of :name, :maximum => 30
	validates_presence_of :address
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:name, :description, :price, :total_in_shelf, :total_in_vault, :store_id)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

	# GET /services
	def index
	end

	def stores
		if params[:st_id]
			@st_id = params[:st_id]
    		@articles = Article.where(:store_id => @st_id)
    		render 'articles_by_store.json.jbuilder'
    	else
    		@stores = Store.all
			render 'stores.json.jbuilder'
		end

	end

	def articles
		@articles = Article.all
		render 'articles.json.jbuilder'
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render action: 'show', status: :created, location: @store }
      else
        format.html { render action: 'new' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url }
      format.json { head :no_content }
    end
  end

  private
    def set_store
      @store = Store.find(params[:id])
    end

    def store_params
      params.require(:store).permit(:name, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Supershoes"
		if page_title.empty?
		  base_title
		else
		  "#{base_title} | #{page_title}"
		end
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
	def getStoreName id
		st = Store.where(:id => id).first
		st.name unless st.nil?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :total_in_shelf %><br>
    <%= f.number_field :total_in_shelf %>
  </div>
  <div class="field">
    <%= f.label :total_in_vault %><br>
    <%= f.number_field :total_in_vault %>
  </div>
  <div class="field">
    <% stores_array = Store.all.map { |st| [st.name, st.id] } %>
    <%= f.label :store_id, 'Select store' %><br>
    <%= f.select :store_id, stores_array %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, 'Edit Article') %>
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% provide(:title, 'Articles') %>
<h1>Listing articles</h1>

<p><%= link_to 'New Article', new_article_path, class: 'btn-small btn-primary' %></p>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Total in shelf</th>
      <th>Total in vault</th>
      <th>Store</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.description %></td>
        <td><%= article.price %></td>
        <td><%= article.total_in_shelf %></td>
        <td><%= article.total_in_vault %></td>
        <td><%= getStoreName(article.store_id) %></td>
        <td>
          <%= link_to 'Show', article, class: 'btn-small btn-info' %>
          <%= link_to 'Edit', edit_article_path(article), class: 'btn-small btn-info' %>
          <%= link_to 'Destroy', article, class: 'btn-small btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/articles/new.html.erb
<% provide(:title, 'New Article') %>
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% provide(:title, 'Article') %>
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @article.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @article.price %>
</p>

<p>
  <strong>Total in shelf:</strong>
  <%= @article.total_in_shelf %>
</p>

<p>
  <strong>Total in vault:</strong>
  <%= @article.total_in_vault %>
</p>

<p>
  <strong>Store:</strong>
  <%= @article.store_id %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Developed by <a href="https://github.com/VictorGuzman">Victor Guzman</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<nav>
				<a class="brand" href="#">Supershoes</a>
				<ul class="nav">
					<li><%= link_to "Home", :home %></li>
					<li><%= link_to "Stores", :stores %></li>
					<li><%= link_to "Articles", :articles %></li>
					<li><%= link_to "Services", :services %></li>
					<li><%= link_to "Help", :help %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
  		<%= yield %>
  		<%= render 'layouts/footer' %>
  	</div>
  </body>
</html>

app/views/services/index.html.erb
<% provide(:title, 'Services') %>
<div>
	<h1>Services</h1>
	<p>
		Supershoes provides a plataform to interact with a future Android version of this application. There are three main JSON-based RESTful services that Supershoes provides right now. Here you will find how to verify that the JSON responses for every request are correct.
	</p>

	<h4>List all stores</h4>
		<p>To verify the JSON response for this request type in your browser's navigation bar:</p>
		<div class="center">
			<code>http://supershoes.herokuapp.com/services/stores</code>
		</div>
		<p>If you are in a local environment you should type:</p>
		<div class="center">
			<code>http://localhost:3000/services/stores</code>
		</div>
		<br/>

	<h4>List all articles</h4>
		<p>To verify the JSON response for this request type in your browser's navigation bar:</p>
		<div class="center">
			<code>http://supershoes.herokuapp.com/services/articles</code>
		</div>
		<p>If you are in a local environment you should type:</p>
		<div class="center">
			<code>http://localhost:3000/services/articles</code>
		</div>
		<br/>

	<h4>List all the articles that are in a specific store</h4>
		<p>To verify the JSON response for this request type in your browser's navigation bar:</p>
		<div class="center">
			<code>http://supershoes.herokuapp.com/services/articles/stores/:id</code>
		</div>
		<p>If you are in a local environment you should type:</p>
		<div class="center">
			<code>http://localhost:3000/services/articles/stores/:id</code>
		</div>
		<p>You should replace <code>:id</code> with a store ID.</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div>
	<h1>Help</h1>
	<p>
		If you want to view the code you can download the <a href="https://github.com/VictorGuzman/supershoes">repository</a> and follow the instructions to get it running in your local system.
	</p>
	<%= link_to "Download Repository", 'https://github.com/VictorGuzman/supershoes', class: "btn btn-small btn-primary" %>
</div>

app/views/static_pages/home.html.erb
<div class="center">
	<h1> Welcome to Supershoes</h1>
	<p>
		This is an exercise <a href="http://rubyonrails.org/">Ruby on Rails</a> app. Its only pourpose is to show Ruby on Rails functionality in a fake Supershoes store and to test JSON based RESTful responses. This is a deployed version of the proyect using <a href="https://www.heroku.com/">Heroku</a>. If you want to view the code you can download the <a href="https://github.com/VictorGuzman/supershoes">repository</a> and follow the instructions to get it running in your local system.
	</p>
	<%= link_to "Download Repository", 'https://github.com/VictorGuzman/supershoes', class: "btn btn-small btn-primary" %>
</div>
<%= link_to image_tag("supershoes.png", alt: "Supershoes"), '#' %>

app/views/stores/_form.html.erb
<%= form_for(@store) do |f| %>
  <% if @store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% @store.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<% provide(:title, 'Edit Store') %>
<h1>Editing store</h1>

<%= render 'form' %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<% provide(:title, 'Stores') %>
<h1>Listing stores</h1>

<p><%= link_to 'New Store', new_store_path, class: 'btn-small btn-primary' %></p>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.address %></td>
        <td>
          <%= link_to 'Show', store, class: 'btn-small btn-info' %>
          <%= link_to 'Edit', edit_store_path(store), class: 'btn-small btn-info' %>
          <%= link_to 'Destroy', store, class: 'btn-small btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/stores/new.html.erb
<% provide(:title, 'New Store') %>
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<% provide(:title, 'Store') %>
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @store.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>